### PR TITLE
Splitting the package into modules

### PR DESCRIPTION
**Pull request by DmitriyHolovnia**
Splitting makes it possible to use only the necessary modules in the project. There is a plan to add a module for SwiftUI.

### CODE REVIEW

**Review by OleksandrKulyk — COMMENTED** [review]
The more I think about it, the less likely it seems that someone will want not to include one of these two modules, given that we already use both Foundation and UIKit on most of our apps.
It feels more beneficial to divide the existing package into modules by their purpose, not related libraries. Here is my draft on how files can be grouped:

- CellsHelpers - ReusableCell.swift, UICollectionView+extensions.swift, UITableView+extensions.swift
- CollectionsHelpers - Array+extensions.swift, Collection+indexPath
- LayoutHelpers - NSLayoutConstrain+extensions, UILayoutPriority+extensions.swift, UIView+extensions.swift
- UIHelpers - NibInitializable.swift, CACornerMask+extensions.swift, `roundCornersContinuously` method from UIView+extensions.swift

And don't forget to update the tests as well.
Anyway, huge thanks for this initiative and SwiftUI preparations 💯

**Comment by scaaales** [comment]
I don't think dividing by purpose is a great idea. If package is added without Package.swift file (with Xcode build in Package Dependencies tab inside project settings) only way to change selected target's is to delete and add package again, to my knowledge. So, i think, it is better so have as few modules as possible. Modules based on main framework extended in module is a great idea. 
But i agree that tests should be fixed. I believe run_tests.yml need to be updated for that.
…

**Comment by OleksandrKulyk** [comment]
@scaaales Good point about the number of modules. Indeed, we might end up with a ton of them.
As for the need to re-add the dependency to include the new module - it is true. I don't think there is a way for a seamless update even for these two modules split, so we will probably need to bump the major version.

@DmitriyHolovnia As for the changes I suggested (TLDL, feel free to ignore them):
Right now (UIKit-only), IMHO, it is tempting to go with purpose-based separation. However, considering further plans for SwiftUI - I can see why you may want to have a separate Foundation module. Such an approach will allow the following combinations for two different UI styles:
Foundation + UIKit,
Foundation + SwiftUI.

**Comment by DmitriyHolovnia** [comment]
@scaaales you can add targets here:
Screenshot 2022-06-10 at 5 29 04 PM
@AlexanderKulyk I like your idea. I will work on it soon.

**Comment by scaaales** [comment]
improved and finished in https://github.com/uptechteam/Uptech-iOS-Helpers/pull/7

**Pull request closed without merging**
